### ISSUE TITLE
Ticker may stop working soon.

### ISSUE THREAD

**Issue by hako** [hako/bbcli#1]
BBC will introduce a new responsive site (view site on a tablet) which there is no ticker. 
 [However it's still up for consideration.](http://www.bbc.co.uk/blogs/internet/entries/6c02bec0-6c27-3db6-9295-1dcab645d567?postId=121092802&initial_page_size=20#comment_121092802)

**Comment by return** [comment]
Once the ticker has finished initialising, bbcli keeps crashing.

**Comment by hako** [comment]
Yeah, they switched the old ticker off. I've downgraded to the old android app and it's blank. Will fix soon.

**Comment by hako** [comment]
EDIT: @return  It should be fixed now, oddly enough data from the ticker is still there.
